---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package and php library for apache2
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.10"

 
